### ISSUE TITLE
Add a convenience handler for crypto_box_seal

### ISSUE THREAD

**Issue by rapus95** [Gnimuc/Sodium.jl#1]
Pack a convenience function which inits if necessary and automatically allocates the cipher memory and infers the msg length, i.e. such that the following scenario works:
```
using Sodium
cipher = Sodium.seal(msg, pk)
```
here `pk` may be a String, Base.SecretBuffer etc. and `msg` be either a String or a Vector{UInt8}.

Since you wrapped the direct bindings in Sodium.LibSodium, adding convenience in Sodium seems like an actually good layout. 😄

**Comment by rapus95** [comment]
A very basic (and probably errorprone) first iteration could be like that:
```julia
@eval Sodium function seal(msg, pk)
        sodium_init() < 1 && error("something didn't work")
        len = sizeof(msg)
        ciphertext = Vector{Cuchar}(undef, crypto_box_SEALBYTES + len)
        crypto_box_seal(ciphertext, msg, len, pk)
        return String(ciphertext)
      end
```
That's how I monkeypatched it for now 😁

EDIT: Replaced `length(msg)` by `sizeof(msg)` as msg can be a unicode string in which case we need to cover the fact that a single char can take multiple bytes.

**Comment by Gnimuc** [comment]
> Since you wrapped the direct bindings in Sodium.LibSodium, adding convenience in Sodium seems like an actually good layout. 😄

Yeah, that's the plan, but I don't have the bandwidth of maintaining the helper APIs. 😂 I'm actually looking for someone to help with maintaining this package.

**Comment by Gnimuc** [comment]
I've read your message on the slack. But I only know how to maintain the wrapper generator part of the package, I actually never use this package. @bramtayl may chime in with the Github secrets stuff.

**Comment by bramtayl** [comment]
I'm kinda in the same boat as @Gnimuc. My implementation in OnlinePackage is similar to yours;

```
raw_encoded = Vector{Cuchar}(undef, crypto_box_sealbytes() + length(private_key))
error_code = crypto_box_seal(
    raw_encoded,
    private_key,
    length(private_key),
    sodium_key
)
if error_code != 0
    error("Error using libsodium.crypto_box_seal")
end
```

**Comment by rapus95** [comment]
@bramtayl so I guess your private key is ascii only? 😄
Do you also need it to enable testing of private packages?

**Comment by Gnimuc** [comment]
I'm not 100% sure what I'm talking about, so just take this with a grain of salt. The encryption algorithms used in Github secrets and the default one used in libsoduim's `crypto_box_seal` may mismatch.

https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#about-encrypted-secrets

https://libsodium.gitbook.io/doc/public-key_cryptography/sealed_boxes#algorithm-details

**Comment by bramtayl** [comment]
I got to that code via guess and check, so no idea tbh

**Comment by rapus95** [comment]
I think those will be working together flawlessly:
https://developer.github.com/v3/actions/secrets/#create-or-update-a-secret-for-a-repository

**Comment by rapus95** [comment]
v1.1 contains it, including tests.
